### PR TITLE
Refactor: move bubble from home page to analytics

### PR DESCRIPTION
**Pull request by jotaesteves**
- moves Bubble view from **Homepage** `/` - to -> **Analytics** `/analytics` view

image

image

### CODE REVIEW

**Review by thomas-burko — APPROVED** [review]
Please check the other PR's for my feedback before merge.

**Comment by jotaesteves** [comment]
> Please check the other PR's for my feedback before merge.

I´ve checked and resolved the discussion is it ok to merge after https://github.com/trustbit/Contexture/pull/141 is merged?

**Comment by thomas-burko** [comment]
Linting fails: https://github.com/trustbit/Contexture/actions/runs/7015471100/job/19084846328?pr=142

Rest is fine 👍

**Comment by jotaesteves** [comment]
let me lint fix and push

**Pull request merged**
